// Generated by https://quicktype.io

import { Asset } from "./IProductContentResponse";

export interface IPostContentResponse {
  sys: IPostContentResponseSys;
  total: number;
  skip: number;
  limit: number;
  items: PostItem[];
}

export interface PostItem {
  metadata: Metadata;
  sys: ItemSys;
  fields: Fields;
}

export interface Fields {
  title: string;
  author: string;
  post: Post;
  banner: Asset;
}

export interface Post {
  nodeType: string;
  data: Data;
  content: PostContent[];
}

export interface PurpleContent {
  nodeType: PurpleNodeType;
  value?: string;
  marks?: any[];
  data: Data;
  content?: PostContent[];
}

export interface PostContent {
  nodeType: FluffyNodeType;
  data: Data;
  content: PurpleContent[];
}

export interface Data {}

export enum PurpleNodeType {
  ListItem = "list-item",
  Text = "text",
}

export enum FluffyNodeType {
  OrderedList = "ordered-list",
  Paragraph = "paragraph",
}

export interface Metadata {
  tags: any[];
}

export interface ItemSys {
  space: ContentType;
  type: string;
  id: string;
  contentType: ContentType;
  revision: number;
  createdAt: string;
  updatedAt: string;
  environment: ContentType;
  locale: string;
}

export interface ContentType {
  sys: ContentTypeSys;
}

export interface ContentTypeSys {
  type: string;
  linkType: string;
  id: string;
}

export interface IPostContentResponseSys {
  type: string;
}
